services:
  vivesbankapi:
    image: vivesbankapi
    build:
      context: .
      dockerfile: VivesBankApi/Dockerfile
    ports:
      - "5099:8080"
    depends_on:
      - mongo-db
      - postgres
      - ftp-server
    networks:
      - banco-network
    environment:
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT

  mongo-db:
    container_name: tienda-mongo
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "pass"
      MONGO_INITDB_DATABASE: "banco"
    volumes:
      - mongo-init:/data/db
      - ./VivesBankApi/initMongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    networks:
      - banco-network
  
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: banco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - banco-network

  redis:
    image: redis:latest
    container_name: Redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/dаta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  ftp-server:
    image: fauria/vsftpd
    container_name: ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      FTP_USER: "myuser"
      FTP_PASS: "mypass"
      PASV_ADDRESS: "127.0.0.1"
      PASV_MIN_PORT: 21000
      PASV_MAX_PORT: 21010
      FTP_HOME: "/home/vsftpd"
    volumes:
      - "./ftp_data:/home/vsftpd"
    networks:
      - banco-network

volumes:
  mongo-init:
  postgres_data:
  ftp-data:

networks:
  banco-network:
