services:
  vivesbankapi:
    image: vivesbankapi
    build:
      context: .
      dockerfile: VivesBankApi/Dockerfile
    ports:
      - "5099:8080"
    depends_on:
      - mongo-db
      - postgres
    networks:
      - banco-network
    environment:
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT


  mongo-db:
    container_name: tienda-mongo
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "pass"
      MONGO_INITDB_DATABASE: "banco"
    volumes:
      - mongo-init:/data/db
      - ./VivesBankApi/initMongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    networks:
      - banco-network
  
  
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: banco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - banco-network


volumes:
  mongo-init:
  postgres_data:

networks:
  banco-network: